version: "3.8"
services:
  db:
    image: "postgres:14.1-alpine"
    container_name: "some-postgres"
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ViaTabloid
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword

  backend:
    build:
      context: ./
    image: 'httprequest:latest'
    container_name: 'investment-platform-container'
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - TASTYTRADE_USERNAME=${TASTYTRADE_USERNAME}
      - TASTYTRADE_PASSWORD=${TASTYTRADE_PASSWORD}

volumes:
  db:
    driver: local
