version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  
  backend:
    build:
      context: ./
    image: 'investmentplatform:dev'   
    environment:
      - TASTYTRADE_USERNAME=${TASTYTRADE_USERNAME}
      - TASTYTRADE_PASSWORD=${TASTYTRADE_PASSWORD}
      - TASTYTRADE_ACCOUNT_NUMBER=${TASTYTRADE_ACCOUNT_NUMBER}
    env_file:
      - .env
    container_name: 'investment-platform-container'
    ports:
      - 8080:80

volumes:
  postgres_data:
