// <auto-generated />
using InvestmentPlatform.DBAcces;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InvestmentPlatform.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240803203549_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InvestmentPlatformAPI.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppLastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AppUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TastytradeAccountNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TastytradeEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TastytradePassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
